openapi: 3.0.0
info:
  title: KOUST OAUTH2.0
  version: '1.0'
servers:
  - url: 'https://koustapp.com/apex/rest'
paths:
  /public_authentication/generate_client:
    parameters: []
    get:
      summary: Get credentials needed for access token
      tags: []
      operationId: get-client-credentials
      description: Retrieve the client_id and client_secret needed to obtain an access token.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples:
              Example:
                value:
                  username: contact@koustuser.fr
                  password: 2efb#457
        description: The username and password used to connect on Koust
components:
  schemas:
    Client-Response:
      title: Client Response
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
      x-examples:
        Example:
          client_id: string
          client_secret: string
    Token-Response:
      title: Token Response
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: string
      x-examples:
        Example:
          access_token: string
          token_type: bearer
          expires_in: string
  securitySchemes: {}
