openapi: 3.0.0
info:
  title: KOUST OAUTH2.0
  version: '1.0'
  description: ''
servers:
  - url: 'https://koustapp.com/apex/rest/public_authentication'
    description: Auth URL
paths:
  generate_client:
    parameters: []
    post:
      summary: Generate Client Token
      operationId: postgenerate_client
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client-Response'
      description: Retrieve the client_id and client_secret needed to obtain an access token.
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        description: The username and password used to connect on Koust
components:
  schemas:
    Client-Response:
      title: Client Response
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
      x-examples:
        Example:
          client_id: string
          client_secret: string
    Token-Response:
      title: Token Response
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: string
      x-examples:
        Example:
          access_token: string
          token_type: bearer
          expires_in: string
  securitySchemes: {}
tags:
  - name: OAuth2.0
