openapi: 3.0.0
info:
  title: KOUST OAUTH2.0
  version: '1.0'
  description: ''
servers:
  - url: 'https://koustapp.com/apex/rest/public_authentication'
    description: Auth URL
paths:
  /generate_client:
    parameters: []
    post:
      summary: Generate Client Token
      operationId: postgenerate_client
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client-Response'
              examples:
                Example:
                  value:
                    client_id: GxKjEJQ8Y0XQVYODVzFTIA..
                    client_secret: BHHhx6ql13T3qYIk7dOeqQ..
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Trial period expired:
                  value:
                    message: 'Your trial period has expired, please contact administrator.'
                Subscription expired:
                  value:
                    message: 'Your subscription has expired, please contact administrator.'
                Invalid password:
                  value:
                    message: Please provide a valid password.
                Invalid username:
                  value:
                    message: Please provide a valid username.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Authentication failed:
                  value:
                    message: 'Authentication failed, please verify credentials.'
      description: Retrieve the client_id and client_secret needed to obtain an access token.
      parameters:
        - $ref: '#/components/parameters/Content-Type'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        description: The username and password used to connect on Koust
  /get_access_token:
    post:
      summary: Get Access Token
      operationId: get_access_token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token-Response'
              examples:
                Example:
                  value:
                    access_token: 2ys6njd9OCmfsAv-fRKsdw
                    token_type: bearer
                    expires_in: 3600
      description: |-
        Use access token to authenticate on Koust Endpoints, access token is link to a Koust user account.

        Note:

         - Access Tokens expire after 1 hour.
      parameters:
        - schema:
            type: string
          in: query
          name: client_id
          required: true
        - schema:
            type: string
          in: query
          name: client_secret
          required: true
components:
  schemas:
    Client-Response:
      title: Client Response
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
      x-examples:
        Example:
          client_id: string
          client_secret: string
    Token-Response:
      title: Token Response
      type: object
      x-examples:
        Example:
          access_token: string
          token_type: bearer
          expires_in: int
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
  securitySchemes: {}
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
      description: Resource MIME
tags:
  - name: OAuth2.0
